### ISSUE TITLE
Invalid Autostart Path

### ISSUE THREAD

**Issue by petrleocompel** [vividnightmare/g510s#1]
I think should be `/usr/local/bin/g510s`
https://github.com/vividnightmare/g510s/blob/1a6d00ad90ab938c5c33ae187974e750ec39f4e4/g510s.desktop#L4
Also i really thank you. Best working driver what i found in years... :confetti_ball: :+1: :1st_place_medal:

**Comment by vividnightmare** [comment]
If you find more of these feel free to let me know.  The desktop file was situated for the final location of installed files through a package manager, but the source package should follow /usr/local.
