### ISSUE TITLE
cannot launch g15-config on eoan

### ISSUE THREAD

**Issue by joe-mojo** [vividnightmare/g510s#10]
g15-config prints:
```
Traceback (most recent call last):
  File "/usr/local/bin/g15-config", line 23, in <module>
    import gconf
ImportError: No module named gconf
```

maybe some gconf dependency missing ?

Edit: no more `python-gconf` package in Ubuntu 19.10... I guess you'll need to provide it

**Comment by vividnightmare** [comment]
So, where are you getting this issue exactly?  G510s isn't written in and doesn't use any Python.

**Comment by joe-mojo** [comment]
OMG according to its path, g15-config doesn't come from you package... back in time g15 package came with some utilities written in Python. I had to compile myself latest versions before russo79.com disappeared !

Ok, you can close. By the way, why g510s package is in conflict with g15daemon ? how to configure keyboard if the is no config utility anymore ?

**Comment by vividnightmare** [comment]
G510s provides g15daemon.
