### ISSUE TITLE
g510s should have a service

### ISSUE THREAD

**Issue by joe-mojo** [vividnightmare/g510s#12]
g510s is nice to configure colors and keys, but when you stop it, the keyboard stops too.
Perhaps a gui + a service couldbe a goo combination, like ckb-next did for Corsair mice and keyboards ?

**Comment by vividnightmare** [comment]
This is essentially provided.  It's a one step solution to use the keyboard.  If you're suggesting to split them into separate packages, I don't see the need for that but patches are welcome.
