### ISSUE TITLE
G510s for Linux Mint 19.3 Cinnamon

### ISSUE THREAD

**Issue by NBGladbach** [vividnightmare/g510s#14]
Hello,

at first sorry for my bad english :)

I´ve installed the PPA and in the beginning everything worked. After a few restarts, however, no more.
The keyboard shows the G510s logo again and the software no longer starts. If I then try to write something, the key (e.g. B) remains permanently active and the keyboard stops responding.

Is it because of my Linux version or have I made any mistakes?

I am new to Linux and I am not very familiar with it.

**Comment by vividnightmare** [comment]
Verify you have G510s installed.

`apt policy g510s`

If it is not installed, install it.

`sudo apt install g510s`

If it is installed, run it.

`g510s`

**Comment by NBGladbach** [comment]
Ok thank you very much, but how can I write any G-Macros? Alt/F4 for example?

**Comment by vividnightmare** [comment]
You write your "macros" using X11 tools and then use G510s to execute the commands.

For example, I would use `xdotool key alt+F2` to open a command prompt.  To do this with G510s, you would enter this for one of your G keys in the GUI.

![Screenshot_20200120_113402](https://user-images.githubusercontent.com/4257551/72749975-c8d8ff00-3b78-11ea-8687-188fe1db957b.png)

Be sure to end your commands with `&` to run them in the background and don't forget to save your settings in G510s.

If you want more detailed command strings, you'll need to write your own scripts.
