### ISSUE TITLE
Add support for Ubuntu Focal Fossa (20.04)

### ISSUE THREAD

**Issue by localyost3000** [vividnightmare/g510s#15]
Trying to get earlier versions working, but there appear to be a couple differences, preventing it from running. More specifically, I get this error when trying to run g510s

`undefined symbol: g15r_G15FPrint`

I know this symbol come from libg15render, and I have already tried uninstalling and reinstalling libg15render-dev, but nothing changes.

**Comment by vividnightmare** [comment]
Should be able to satisfy this with `apt install libg15render1`

I'll publish a Focal PPA at some point today given I don't forget.

**Comment by vividnightmare** [comment]
Appears to work on my end.  Sorry for the delay.  Are you still having issues?

**Comment by localyost3000** [comment]
Sorry for the long delay on response, but I am still getting the same error. I am starting over from scratch and have gotten stuck at this same error, even after installing the package listed above. I'll keep hacking at it

**Comment by vividnightmare** [comment]
`sudo add-apt-repository ppa:vivnet/g510s`
`sudo apt update`
`sudo apt install g510s`
`g510s &`

**Comment by localyost3000** [comment]
no dice, same error. probably something in my system. oh well, maybe someday I can try again on a fresh install.

**Comment by localyost3000** [comment]
Just wanted to update that on a fresh install of Pop!OS 20.10, the focal ppa worked like a dream! Must have been something odd about my setup in my previous install of ubuntu. Thank you for this tool and for maintaining the ppa!

Next I want to to try and figure out how to port LCDSirReal to this system... Any thoughts on that would be hugely helpful.

**Comment by vividnightmare** [comment]
Is it open source?  Kind of hard to port something you can't get the source for.

Beyond that, G510s supports any screens written for g15daemon (libg15daemon-client).
One of those, g15stats, probably already does everything you want, is open source, and included in the ppa.

**Comment by localyost3000** [comment]
I do not think it is open source, so I will probably not have much luck porting  (or recreating) it. 

Page is here if you are interested https://www.linkdata.se/software/lcdsirreal/

I will check out g15stats though, thanks again for making all of this available!

**Comment by GimmeBamba** [comment]
Do you have an exe of LCDSirReal? I'm looking for one and the site is down.
