### ISSUE TITLE
Macro's do  not work (Ubuntu 19.10)

### ISSUE THREAD

**Issue by Sutima** [vividnightmare/g510s#16]
Logitech G510s with Ubuntu 19.10 installed Launchpad PPA `https://launchpad.net/~vivnet/+archive/ubuntu/g510s`
I can adjust the backlight colour, but not assigning macros.
Let me know what info you need.

Msg in terminal reads <pre> /usr/bin/g510s
G510s: found device 046d:c22d
G510s: error calling bind
G510s: unable to initialise server at port 15550

(g510s:4108): Gdk-<font color="#CC58CC"><b>CRITICAL</b></font> **: <font color="#0039AA">14:04:36.019</font>: gdk_window_thaw_toplevel_updates: assertion &apos;window-&gt;update_and_descendants_freeze_count &gt; 0&apos; failed
</pre>

**Comment by vividnightmare** [comment]
First thing, macros are simply not supported, and they won't be.

However, you can script your own macros/events/etc and bind those to the keys you choose by using X11 tools or whatever you have available.

If you want to implement a true macro system like what you would find with the official software, for example, patches are certainly welcome.

As for your errors, this is an internal network system that allows external screens to connect and display on the LCD.
