### ISSUE TITLE
PopOS! - Ubuntu 20.04

### ISSUE THREAD

**Issue by JacobWarners** [vividnightmare/g510s#17]
Trying to set this up for a friend

Program opens and looks like it's working, but the terminal is saying it's not detecting the device.

Says
G510S: Failed to initialize libg15
G510S: waiting for device
G510S: Failed to load module "appmenu-gtk-module"
G510S: Failed to load module "canberra-gtk-module"

The keyboard itself doesn't have the macro lights or the display change from g510s.

Any help would be appreciated.

**Comment by vividnightmare** [comment]
Do you have the appropriate device?

Try `lsusb` and you should see something like the following in the list

`Bus 001 Device 005: ID 046d:c22e Logitech, Inc. G510 Gaming Keyboard onboard audio`

**Comment by JacobWarners** [comment]
Thanks for the quick reply! 

`Bus 001 Device 007: ID 046d:c22d Logitech, Inc. G510 Gaming Keyboard`

So it seems almost the same, but not quite. If you have any suggestions or if it wont work I'm happy to give it a try~~

**Comment by vividnightmare** [comment]
Did you install with the PPA?  https://launchpad.net/~vivnet/+archive/ubuntu/g510s

This is the easiest way to get everything working.

You need to load udev rules to allow access to the device from userspace.

See https://github.com/vividnightmare/g510s/blob/master/99-g510s.rules

and https://github.com/vividnightmare/g510s/blob/master/debian/postinst

for how the packaging does this automagically.
