### ISSUE TITLE
Linux Mint

### ISSUE THREAD

**Issue by MabeyC** [vividnightmare/g510s#18]
Hello,

I was wondering if your code would work fine with [Linux Mint 20 "Ulyana" -Cinnamon](https://linuxmint.com/edition.php?id=281)?

Thank you for putting this repo together.

CM

**Comment by vividnightmare** [comment]
If I'm not mistaken this release is equivalent to Ubuntu 20.04 which is already published in the PPA.

https://github.com/vividnightmare/g510s/blob/master/README.md

https://launchpad.net/~vivnet/+archive/ubuntu/g510s

**Comment by MabeyC** [comment]
Thank you,

I've run into some dependency speed-bumps along the way. Could you help me with the following?

Added PPA
apt-get install
chmod +x configure
./configure
_Here's the hiccup:_
```
checking for main in -lusb... no
configure: error: "libusb not found. please install it"
```
_(I first tried libusb-1.0.0-dev and re-ran the configure file, same error._

I then downloaded [libusb 1.0.23](http://linuxfromscratch.org/blfs/view/svn/general/libusb.html), but then I'm getting stuck with an error of libudev header not installed. 
```
configure: error: udev support requested but libudev header not installed
```

I'm new to Linux, so I could very well be running down a rabbit hole I don't need to. Any thoughts?

Edit: formatting/link

**Comment by vividnightmare** [comment]
sudo add-apt-repository ppa:vivnet/g510s
sudo apt update
sudo apt install g510s

**Comment by MabeyC** [comment]
Excellent. Thank you very much!
