### ISSUE TITLE
Filling syslog due to USB device not being initialized

### ISSUE THREAD

**Issue by CedricReichenbach** [vividnightmare/g510s#20]
I had noticed that my `/var/log/syslog` (and some other files there) had grown huge (~85 GiB each, until the disk was full). Peeking into it showed that an error had been repeatedly logged, and it was related to g510s. There were approximately 600 million such lines, accumulated over a few hours.

Unfortunately, I cleared the files before thinking of writing down the message somewhere, but it was something along the lines of "USB device X was not initialized before it was used".

After a forced restart, this did not happen again, and I'm not sure if it ever happened before. The application was configured to always start with the system.

HTH

**Comment by vividnightmare** [comment]
If it happens again, give me a sample of what it's logging specifically and we'll see if something needs to be done.

I've used this for years with my keyboard and never noticed anything like this so hopefully it's not something you'll encounter again.

If you notice the screen isn't working properly, try unplugging and replugging the device and it should initialize with the software.
