### ISSUE TITLE
Update PPA to Ubuntu Debian 22.04

### ISSUE THREAD

**Issue by greenwoodmultimedia** [vividnightmare/g510s#24]
Hi !

I have a Logitech keyboard g510s and I saw your great software on Github. I tried installing it through your ppa but it seems to not support my version of my OS.

I am running pop-os that is based on Ubuntu Debian 22.04.

Thank you for your great software and I hope you have a great day !

**Comment by vividnightmare** [comment]
Publishing now, should only take a few minutes.

https://launchpad.net/~vivnet/+archive/ubuntu/g510s

**Comment by greenwoodmultimedia** [comment]
Thank you very much @vividnightmare !
