### ISSUE TITLE
How should you install this?

### ISSUE THREAD

**Issue by jtagcat** [vividnightmare/g510s#3]
I don't know even what to google for.. How should I get it installed on my system? Thanks.

**Comment by petrleocompel** [comment]
Well there is little problem on Ubuntu 18.04 with dependencies but still it is installable.
You need to install [vividnightmare/libg15](https://github.com/vividnightmare/libg15) via automake and after that you can install g510s with make. That's all.

For me it was simillar with installation of gnome15 project. I even described a little bit how to use automake an autoconf in [my fork of gnome15](https://github.com/petrlecompel/gnome15) for Ubuntu 16.04.

**Comment by petrleocompel** [comment]
I think actual problem here is "missing documentation".
You still can make a fork and describe how to compile and install for both projects and then make a pull request :sunglasses:. I would give you :+1: for that. And may one day we would see release of this project.

**Comment by RasmusKallas** [comment]
if logitech would buy your project instead of blu and harmony, gave official support, much cheaper and bigger improvement :smile:

**Comment by RasmusKallas** [comment]
@petrleocompel I've gotten used to `alias ag='sudo apt --yes install'` how do i install with automake? what's the difference between make and automake?

**Comment by vividnightmare** [comment]
Simple build and install instructions are found in g510s/INSTALL, including dependencies.

There is a ppa for ubuntu 18.04 at https://launchpad.net/~vivnet/+archive/ubuntu/g510s?field.series_filter=bionic if you would prefer to use that.

**Comment by jtagcat** [comment]
@vividnightmare The ppa worked, but the real question is, how do you get libg15 to be recognized by g510s? When running g510s I still get an error 'setupLibG15', that's the same reason, why it refused to install in the first place.

**Comment by vividnightmare** [comment]
In theory, failure to initialize libg15 would mean you either don't have it installed or your device isn't supported by the software (not a G510 or G510s).  Of course, there could be a bug as well.

Provide the full console output please, there should be some messages to help understand what is happening.

**Comment by jtagcat** [comment]
```
r@TABHLx:~$ g510s
g510s: symbol lookup error: g510s: undefined symbol: setupLibG15
r@TABHLx:~$ 
```
I have a G510s, but it shows up as a G510
```
r@TABHLx:~$ lsusb
Bus 003 Device 003: ID 046d:c22d Logitech, Inc. G510 Gaming Keyboard
```

**Comment by vividnightmare** [comment]
It sounds like an issue with libg15.  If you built it yourself that's probably where the issue came into play.

I would recommend removing it with make uninstall and recompiling it.  It depends on libusb-0.1 (libusb-0.1-4 and libusb-dev) so make sure you have that installed; the configure script should have complained if it wasn't.

The binary packages from the ppa seem to be working just fine.  I can try to replicate the issue when building from source but I'll need to know which OS and version you're using.

**Comment by petrleocompel** [comment]
@vividnightmare you should definitely write that link to ppa/launchpad somewhere in description or readme of project. You have :+1: from me for that.

**Comment by jtagcat** [comment]
@vividnightmare i reinstalled libusb-0.1-4 and libusb-dev and g510s and then unistalled libg15 and compiled it again and installed it and everything somehow works..
Cool thing you added an extra m-profile with MR key!
[Estonian date on it doesn't fit there and jumbles up or it just doesn't like the 'ä' char, I could change it in settings, but I need it in other places... (should be kolmapäev)](http://i.imgur.com/y2LJG5S.png)

The most major problem (I am on 18.04 Ubuntu Budgie) is the huge tray icon, it forcefully expands budgie panel ([normal](http://i.imgur.com/GnSme4S.png), [hugeicon](http://i.imgur.com/teB5Dmt.png))

Not that I need to, but is there any tool to customize the display?
Also yes please add the ppa to the readme

**Comment by vividnightmare** [comment]
You can change the icon to anything you want by replacing g510s.svg and g510s-alert.svg.  This should be doable with out recompiling the program.  They should be installed in /usr/local/share/g510s.

As for the language issues, I suppose that's a problem with the software not having any type of internationalization; I only know English and I'm not a professional engineer.

You can play around with it to get what you want or just comment out the offending code, which can be found in g510s-clock.c, lines 71 through 77.  You will have to recompile for any changes here to take effect.

If you find something that works it would be nice to see what you've done and perhaps we can merge it into the code.  For now I'm going to close this issue.

**Comment by vividnightmare** [comment]
Additionally, you can hide the date string by pressing the second button from the left beneath the screen.

**Comment by jtagcat** [comment]
There is no g510s folder in /usr/local/share/. Though I found /usr/share/g510s and managed to make the icons smaller.

**Comment by jtagcat** [comment]
Any idea, why I have nothing on the screen other than colour and pressing the screen buttons crashes g510s?
I have no will to recompile it. So no localization...
