### ISSUE TITLE
Use of Undefined Keys

### ISSUE THREAD

**Issue by ocket8888** [vividnightmare/g510s#4]
A fresh clone and `make` shows this when trying to compile g510s-keys.c :

```
gcc -Wall -c g510s-keys.c -o g510s-keys.o
g510s-keys.c: In function ‘process_keys’:
g510s-keys.c:114:14: error: ‘G15_KEY_PLAY’ undeclared (first use in this function); did you mean ‘G15_KEY_L5’?
   if ((key & G15_KEY_PLAY) && (key & G15_EXTENDED_KEY)
              ^~~~~~~~~~~~
              G15_KEY_L5
g510s-keys.c:114:14: note: each undeclared identifier is reported only once for each function it appears in
g510s-keys.c:114:38: error: ‘G15_EXTENDED_KEY’ undeclared (first use in this function)
   if ((key & G15_KEY_PLAY) && (key & G15_EXTENDED_KEY)
                                      ^~~~~~~~~~~~~~~~
g510s-keys.c:122:14: error: ‘G15_KEY_STOP’ undeclared (first use in this function); did you mean ‘G15_KEY_L5’?
   if ((key & G15_KEY_STOP) && (key & G15_EXTENDED_KEY)
              ^~~~~~~~~~~~
              G15_KEY_L5
g510s-keys.c:130:14: error: ‘G15_KEY_NEXT’ undeclared (first use in this function); did you mean ‘G15_KEY_LIGHT’?
   if ((key & G15_KEY_NEXT) && (key & G15_EXTENDED_KEY)
              ^~~~~~~~~~~~
              G15_KEY_LIGHT
g510s-keys.c:138:14: error: ‘G15_KEY_PREV’ undeclared (first use in this function); did you mean ‘G15_KEY_MR’?
   if ((key & G15_KEY_PREV) && (key & G15_EXTENDED_KEY)
              ^~~~~~~~~~~~
              G15_KEY_MR
g510s-keys.c:146:14: error: ‘G15_KEY_MUTE’ undeclared (first use in this function); did you mean ‘G15_KEY_MR’?
   if ((key & G15_KEY_MUTE) && (key & G15_EXTENDED_KEY)
              ^~~~~~~~~~~~
              G15_KEY_MR
g510s-keys.c:154:14: error: ‘G15_KEY_RAISE_VOLUME’ undeclared (first use in this function); did you mean ‘G15_KEY_READ_LENGTH’?
   if ((key & G15_KEY_RAISE_VOLUME) && (key & G15_EXTENDED_KEY)
              ^~~~~~~~~~~~~~~~~~~~
              G15_KEY_READ_LENGTH
g510s-keys.c:162:14: error: ‘G15_KEY_LOWER_VOLUME’ undeclared (first use in this function)
   if ((key & G15_KEY_LOWER_VOLUME) && (key & G15_EXTENDED_KEY)
```
(unrelated output omitted)

**Comment by vividnightmare** [comment]
Do you have libg15.h?

https://github.com/vividnightmare/libg15

**Comment by ocket8888** [comment]
Yeah, my first pass at trying to get my keyboard to work was to install g15daemon, which depends on that. I can check for it manually when I get home.

**Comment by vividnightmare** [comment]
The binary dependency doesn't normally include the headers that define all the functions and variables, make sure you have the "dev" packages installed.  A list of what's required for G510s is found here: https://github.com/vividnightmare/g510s/blob/master/README.md

**Comment by ocket8888** [comment]
I'm using Arch - `pacman -Ss libg15-dev` doesn't give me anything, that much I remember. Is it a different package name?

**Comment by vividnightmare** [comment]
I'm not very familiar with Arch, but you just need to make sure you install libg15.h.  Additionally, you probably want the updated libg15 I linked above as it includes a fix for the G510/G510s read length.

**Comment by ocket8888** [comment]
alright. Well, like I said, I can do that when I get home, in about 5-ish hours

**Comment by vividnightmare** [comment]
I'll be around.  I don't think anything has changed with GCC that would cause failures, which does happen infrequently with very old stale software like libg15, but Arch is probably shipping a newer toolset than I'm using currently.  That said, it feels like you just need to supply the build dependencies and it should compile and run.

**Comment by ocket8888** [comment]
Alright, so this is much later than I said, but yeah - it's at `/usr/include/libg15.h`

**Comment by ocket8888** [comment]
I think this is the issue though:
```
$ cat /usr/include/libg15.h | grep "G15_KEY"
#define G15_KEYS 2
#define G15_KEY_READ_LENGTH 9
  unsigned int caps; // capability bitfield - G15_LCD|G15_KEYS;
    G15_KEY_G1  = 1<<0,
    G15_KEY_G2  = 1<<1,
    G15_KEY_G3  = 1<<2,
    G15_KEY_G4  = 1<<3,
    G15_KEY_G5  = 1<<4,
    G15_KEY_G6  = 1<<5,
    G15_KEY_G7  = 1<<6,
    G15_KEY_G8  = 1<<7,
    G15_KEY_G9  = 1<<8,
    G15_KEY_G10 = 1<<9,
    G15_KEY_G11 = 1<<10,
    G15_KEY_G12 = 1<<11,
    G15_KEY_G13 = 1<<12,
    G15_KEY_G14 = 1<<13,
    G15_KEY_G15 = 1<<14,
    G15_KEY_G16 = 1<<15,
    G15_KEY_G17 = 1<<16,
    G15_KEY_G18 = 1<<17,
    G15_KEY_M1  = 1<<18,
    G15_KEY_M2  = 1<<19,
    G15_KEY_M3  = 1<<20,
    G15_KEY_MR  = 1<<21,
    G15_KEY_L1  = 1<<22,
    G15_KEY_L2  = 1<<23,
    G15_KEY_L3  = 1<<24,
    G15_KEY_L4  = 1<<25,
    G15_KEY_L5  = 1<<26,
    G15_KEY_LIGHT = 1<<27
```
the keys you're using aren't in the header, meaning it's probably out of date

**Comment by vividnightmare** [comment]
Those are all defined in libg15.h

https://github.com/vividnightmare/libg15/blob/132f4433347eb45b331abee9f5f06dce44db9ec8/libg15.h#L170

A quick package search of Arch reveals that libg15 1.2.7 is provided, yet the git repository linked is version 1.3.1.

**Comment by ocket8888** [comment]
Yeah, I just finished downloading and compiling libg15 (from your patched repo) and libg15render (Arch package repos have out-of-date version that doesn't provide `g15r_FPrint`), and the build is working now. Highly annoying that those are out of date in a rolling distribution

**Comment by vividnightmare** [comment]
It's because all of this software is basically dead and not maintained for years.

Exactly why I wrote this so I could use all the features of my keyboard. :dancing_men:

**Comment by ocket8888** [comment]
Yeah, it's a real shame. I can't play Dota2 without my G13, and there just aren't good drivers for it on Linux.
