### ISSUE TITLE
Possible Bad Linking

### ISSUE THREAD

**Issue by ocket8888** [vividnightmare/g510s#5]
After installing (`make && sudo make install && sudo udevadm control --reload-rules && sudo udevadm trigger`) the g510s executable fails to launch. I tried both the one at `/usr/local/bin/g510s` and the one in the repo directory after building - both fail with the message:

```
g510s: error while loading shared libraries: libg15render.so.1: cannot open shared object file: No such file or directory
```

**Comment by ocket8888** [comment]
I do have the library in question, freshly built from source and located at `/usr/local/lib/libg15render.so.1`

**Comment by vividnightmare** [comment]
I would suspect /usr/local/lib is not in your ld.so.conf

Check /etc/ld.so.conf.d

**Comment by ocket8888** [comment]
Files in that dir only have the paths for `/usr/lib32` and `/usr/lib/libfakeroot`. You're saying I can just drop a new one in there containing `/usr/local/lib`?

**Comment by vividnightmare** [comment]
Which would be why your linker isn't finding a shared object available in /usr/local/lib

**Comment by vividnightmare** [comment]
You could also remove libg15render and tell the configure script you want to install it under a different prefix.

**Comment by ocket8888** [comment]
I might try that, because after adding a new file pointing at `/usr/loca/lib`didn't do anything. Manually setting the `LD_LIBRARY_PATH` before calling the executable did work, though. Of course, now it's not finding my device...

**Comment by vividnightmare** [comment]
You would also need to run ldconfig to update ld.so.cache

**Comment by ocket8888** [comment]
ah. I have no idea how that stuff works. I guess I can close this, but it's weird that the default install directory for these things is in a place where they can't be found by the linker.

**Comment by vividnightmare** [comment]
That would be an issue with Arch Linux philosophy.  Generally packages not maintained by the distribution are installed to /usr/local

I don't know why Arch doesn't like that, you'd have to ask them.
