### ISSUE TITLE
[Packaging Request] Ubuntu 18.10 cosmic

### ISSUE THREAD

**Issue by jrtberlin** [vividnightmare/g510s#7]
Hi, can you please add a package for 18.10 cosmic to your ppa?

**Comment by vividnightmare** [comment]
Yes.  Just let me take a look at the build-deps available in Cosmic, and if there's no significant changes I can push a package to the build queue in a few minutes.

I'm not currently using Cosmic, so I'll need your feedback to verify everything is working after the repository becomes available.

**Comment by jrtberlin** [comment]
Thanks @vividnightmare! I'll try to give my best with the feedback.

**Comment by vividnightmare** [comment]
Packages are now published for Cosmic.

Everything should function after `sudo add-apt-repository ppa:vivnet/g510s`, `sudo apt update`, and `sudo apt install g510s`.  After that just reboot or run the program from its desktop file.

If it doesn't work properly, open a new issue.
